
import React from "react";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/Footer";

import { Cormorant, Sometype_Mono } from 'next/font/google'
import Navbar from "./components/Navbar";

export const FontSometype = Sometype_Mono({
  weight: ["400"],
  subsets: ['latin'],
  variable: '--font-sometype',
})
export const FontCormorant = Cormorant({
  weight: ["300", "400"],
  subsets: ['latin'],
  variable: '--font-cormorant',
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",

// };


export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
}


export default function RootLayout({ children }) {



  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />

        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        {/* <link href="https://fonts.googleapis.com/css2?family=Bodoni+Moda:ital,opsz,wght@0,6..96,400..900;1,6..96,400..900&family=Cormorant:ital,wght@0,300..700;1,300..700&family=Sometype+Mono:ital,wght@0,400..700;1,400..700&display=swap" rel="stylesheet"></link> */}
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, user-scalable=yes"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Navbar>
          {children}

          <Footer />
        </Navbar>
      </body>

    </html>
  );
}
